INCLUDE_PATH = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include"
LIBRARY_PATH = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\Win32"

all: 
	g++ -O3 -Wall -std=c++11 -o multmat multmat.cpp -I$(INCLUDE_PATH) -L$(LIBRARY_PATH) -lOpenCL

